<#
    .SYNOPSIS
        Converts simplified localization format to WolvenKit JSON format.
    .EXAMPLE
        .\convert.ps1
#>

$sourcePath = Split-Path -Parent $MyInvocation.MyCommand.Definition
$targetPath = Join-Path $sourcePath "..\WolvenKit\source\raw\zhincore\chaosmod\"

# Iterate through json files in this folder
foreach ($file in Get-ChildItem -Path $sourcePath -Filter *.json) {
    $content = Get-Content -Raw $file.FullName | ConvertFrom-Json
    $entries = @()

    foreach ($entry in $content.PSObject.Properties) {
        $entries += [ordered]@{
            '$type' = "localizationPersistenceOnScreenEntry"
            "secondaryKey" = "ChaosMod-Effects-$($entry.Name)-Name"
            "femaleVariant" = $entry.Value.name
        }
        $entries += [ordered]@{
            '$type' = "localizationPersistenceOnScreenEntry"
            "secondaryKey" = "ChaosMod-Effects-$($entry.Name)-Desc"
            "femaleVariant" = $entry.Value.description
        }
    }

    $output = [ordered]@{
        "Header" = [ordered]@{
            "_NOTE" = "THIS FILE IS AUTOGENERATED"
            "WolvenKitVersion" = "8.16.1"
            "WKitJsonVersion"  = "0.0.9"
            "GameVersion"      = 2200
            "DataType"         = "CR2W"
        }
        "Data" = [ordered]@{
            "Version" = 195
            "BuildVersion" = 0
            "RootChunk" = [ordered]@{
                '$type' = "JsonResource"
                "cookingPlatform" = "PLATFORM_PC"
                "root" = [ordered]@{
                    "HandleId" = "0"
                    "Data" = [ordered]@{
                        '$type' = "localizationPersistenceOnScreenEntries"
                        "entries" = $entries
                    }
                }
            }
        }
    }

    # Write the output to a file
    $output | ConvertTo-Json -Depth 100 -Compress | Set-Content (Join-Path $targetPath "$($file.BaseName).json.json")

}
