<#
    .SYNOPSIS
        Build script.
    .EXAMPLE
        .\build.ps1
#>

$ErrorActionPreference = "stop"

$modName = "chaosmod"

# Project file paths
$sourcePath = ".\localizations"
$projectPath = ".\WolvenKit"
$rawPath = "$projectPath\source\raw\$modName\localization"
$archivePath = "$projectPath\source\archive\$modName\localization"


# Preparation
New-Item -ItemType Directory -Force -Path $rawPath | Out-Null
New-Item -ItemType Directory -Force -Path $archivePath | Out-Null

$wkitCommand = "cp77tools"
try { if(Get-Command $wkitCommand) { Write-Host -ForegroundColor Cyan "WolvenKit.CLI found." } }
Catch {
    $wkitCommand = "WolvenKit.CLI"
    try { if(Get-Command $wkitCommand) { Write-Host -ForegroundColor Cyan "WolvenKit.CLI found." } }
    Catch {
        Write-Host "WolvenKit.CLI not found! attempting install"
        dotnet tool install --global --add-source ./nupkg WolvenKit.CLI
        if ($LASTEXITCODE -ne 0) {
            $wkitCommand = ""
            Write-Host -ForegroundColor Yellow "Failed to install WolvenKit.CLI. You'll need to import translations manually."
        }
    }
}

# Convert translations
Write-Host "Converting translations..."
# Iterate through json files in this folder
foreach ($file in Get-ChildItem -Path $sourcePath -Filter *.json) {
    Write-Host "  Converting $($file.Name)..."
    $content = Get-Content -Raw $file.FullName | ConvertFrom-Json
    $entries = @()

    foreach ($category in $content.PSObject.Properties) {
        foreach ($entry in $category.Value.PSObject.Properties) {
            $entries += [ordered]@{
                '$type' = "localizationPersistenceOnScreenEntry"
                "secondaryKey" = "ChaosMod-$($category.Name)-$($entry.Name)"
                "femaleVariant" = $entry.Value
            }
        }
    }

    $output = [ordered]@{
        "Header" = [ordered]@{
            "_NOTE" = "THIS FILE IS AUTOGENERATED"
            "WolvenKitVersion" = "8.16.1"
            "WKitJsonVersion"  = "0.0.9"
            "GameVersion"      = 2200
            "DataType"         = "CR2W"
        }
        "Data" = [ordered]@{
            "Version" = 195
            "BuildVersion" = 0
            "RootChunk" = [ordered]@{
                '$type' = "JsonResource"
                "cookingPlatform" = "PLATFORM_PC"
                "root" = [ordered]@{
                    "HandleId" = "0"
                    "Data" = [ordered]@{
                        '$type' = "localizationPersistenceOnScreenEntries"
                        "entries" = $entries
                    }
                }
            }
        }
    }

    # Write the output to a file
    $output | ConvertTo-Json -Depth 100 -Compress | Set-Content "$rawPath\$($file.BaseName).json.json"
}

# Import translations
if ($wkitCommand -ne "") {
    Write-Host "Importing translations..."
    & $wkitCommand convert deserialise "$rawPath" -w "*.json.json" -o "$archivePath"
} else {
    Write-Host -ForegroundColor Yellow "Importing skipped."
}

Write-Host -ForegroundColor Green "Done."
